[package]
name = "BitMapTrieMap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#ahash = "0.8.11"
#hashbrown = "0.14.3"
#roaring = "0.10.3"

[build]
rustflags = "-C opt-level=3 -C target-cpu=native"
