[package]
name = "ringmap"
version = "0.1.0"
edition = "2021"

[dependencies]
#rclite = "0.2.4"
#ahash = "0.8.11"
#hashbrown = "0.14.3"
#roaring = "0.10.3"
dyn-clone = "1.0.17"

[build]
rustflags = "-C opt-level=3 -C target-cpu=native"

[dev-dependencies]
divan = "0.1.14"
rand = "0.8.5"

[[bench]]
name = "basics"
harness = false

[[bench]]
name = "sparse_keys"
harness = false