[package]
name = "pathmap"
version = "0.1.0"
edition = "2021"

[dependencies]
#rclite = "0.2.4"
#ahash = "0.8.11"
#hashbrown = "0.14.3"
#roaring = "0.10.3"
dyn-clone = "1.0.17"
local-or-heap = "0.1.0"
smallvec = {version = "1.13.0", optional = true}
mutcursor = {version = "0.1.9"}
num-traits = "0.2"

[features]
all_dense_nodes = [] # Exclusively use the DenseNode type, which generally performs worse but is useful for compatibility and perf comparisons
counters = [] # Enable features to inspect performance properties of trees
smallvec = ["dep:smallvec"] # Use SmallVec inside the DenseByteNode. Seems to help on very large trees and hurt on small ones

[build]
rustflags = "-C opt-level=3 -C target-cpu=native"

[dev-dependencies]
divan = "0.1.14"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"]}
csv = "1.1.6"

[[bench]]
name = "basics"
harness = false

[[bench]]
name = "sparse_keys"
harness = false

[[bench]]
name = "cities"
harness = false

[[bench]]
name = "shakespeare"
harness = false

[[bench]]
name = "parallel"
harness = false
